title: vRandomBites
email: ricardo.adao@gmail.com
description: >-
  This is my blog and my opinions.
baseurl: "/"
url: "https://vrandombites.co.uk"
twitter_username: ricardonadao
github_username:  ricardonadao

# SEO info
twitter:
  username: ricardonadao
  card: summary
social:
  name: Ricardo Adao
  links:
    - https://twitter.com/ricardonadao
    - https://www.linkedin.com/in/ricardonadao/
    - https://github.com/ricardonadao
    - https://plus.google.com/+RicardoAdao
google_site_verification: ZbHQ1ErXGLxJ68-pSIGslwc1Dq3afLqgeFIGvKl2K9o

# Google Analytics
google_analytics: UAâ€”117546593-1


# Build settings
markdown: kramdown
theme: jekyll-theme-architect
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
